# Ejecute del despliegue automático en la rama main si el linter y los tests de la rama develop resultan exitosos
# Este yml comprobara si el linter y los tests son exitosos desde la rama develop y desplegara la aplicacion en la rama
# main 

name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Lint
      run: |
        npm run lint

    - name: Test
      run: |
        npm test

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3.11.0
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: main
